theme: vv5cv

# Estos colores estan representados en _variables.scss
# cualquier cambio aquí debe ser refeljado en _variables.scss
colors:
  - bluesaur
  - planti
  - silver
  - darks
  - blue
  - red
  - orange
  - green
  - jellow
  - guaya
  - purple
  - gris2
  - tomato

kramdown:
  hard_wrap: true

profile:
  name: Jane Doe
  tagline: Professional Assasin
  picture: http://lorempixel.com/output/fashion-q-c-480-480-8.jpg
  phone: +52(1) 222 000 0000
  email: me@example.com
  address: >-
          The Honorable Charles W. Anderson (Dear Mr. Ambassador:)
          Department of State
          2050 Bamako Place
          Washington, DC 20521-2050
  website: https://example.com

languages:
  es: 100
  en: 90
  jp: 20

software:
  Illustrator:
    icon: android.svg
    skill: 0
  AfterEffects:
    icon: freebsd.svg
    skill: 50
  Rhinoceros:
    icon: github.svg
    skill: 70
  Autocad:
    icon: line.svg
    skill: 100

otherskills:
  machinery:
    modeling:
      icon: playstation.svg
      skills:
        - 3D printing
    cnc:
      icon: angular.svg
      skills:
        - CNC Router
        - Laser Cutting
        - Vynil Cutting

  administrative:
    organization:
      icon: apple.svg
      skills:
        - Slack
        - Email
    management:
      icon: slack.svg
      skills:
        - Scrum
